### ISSUE TITLE
The nav links is invisible but are still clickable?

### ISSUE THREAD

**Issue by loctran016** [jonasschmedtmann/advanced-css-course#75]
I've tested this on both Brave and FireFox. I've tried to fix this and it works. May you update the code please, thanks.

<details>
<summary>My code is here (sass/layout/_navigation.scss)</summary>

```scss
.navigation {
&__link {
            display: none;
    }

&__checkbox:checked ~ &__nav &__list &__item &__link {
        &:link,
        &:visited {
            display: inline-block;
        }
    }
}
```

</details>

https://user-images.githubusercontent.com/64778285/125754742-0c800d4c-b420-4030-a688-9121b2131299.mp4
![2021-07-15 (2)](https://user-images.githubusercontent.com/64778285/125754476-0eab65a1-b58b-493e-856e-8510264703d7.png)
![2021-07-15 (3)](https://user-images.githubusercontent.com/64778285/125754484-84b55020-29b4-4968-89c0-13847ad61572.png)
